galsim: 
	gcc -c galsim.c -o galsim.o -lm -Ofast -march=native -ffinite-math-only -fno-signed-zeros 
	gcc graphics/graphics.o galsim.o -o galsim -lX11 -lm -Ofast -march=native -ffinite-math-only -fno-signed-zeros
